### ISSUE TITLE
CommonModules

### ISSUE THREAD

**Issue by dgonzal** [UHH2/UHH2#121]
Hi 
I think it is great that we have these but I wanted to ask if we could possibly change two things. 
I would like to use it with the 2D-Cut therefore I need to run the jetlep cleaner and change the ordering. 
Of course in the end one needs to do the sorting of jets.

Are there any inconveniences to run it in this order ?

 *  - JetCorrector using the latest PHYS14 corrections for MC
 *  - JetResolutionSmearer  (for MC only)
 *  - ElectronCleaner
 *  - Muon Cleaner
 *  - Tau Cleaner
 *  - JetLepCleaner
 *  - JetCleaner
 *  - HTCalculator
 *  - Sort jets by pT

**Comment by dgonzal** [comment]
@peiffer @rkogler

**Comment by peiffer** [comment]
Hi,
shouldn't the JetCorrector and the JetResolutionSmearer run after the JetLepCleaner?

**Comment by dgonzal** [comment]
Yes you are right it was done this way before. I will implement it and make a pull request .

**Comment by missirol** [comment]
just FYI

in some MC studies done for the Z'->ttbar semileptonic analysis, we saw that applying the JER correction after Jet-Lepton cleaning (JLC) biases the kinematic of the jet, if by JLC one refers to the procedure by which the lepton p4 is subtracted from the jet p4 (if one does jet-lepton cleaning just by removing altogether some jets from the original jet collection, then i don't think the order of JER and JLC makes a difference).

as far as we understood, this is because the JER correction uses the pt of the GenJets, on which lepton-cleaning is not performed, so by doing JERC after JLC one basically is comparing the pt of a GenJet "with" lepton against the pt of a RecoJet "without" lepton, thus the bias.
from the explaination it s clear that the issue affects only topologies where the lepton is expected to be close-to/clustered-in the jet. for this reason, the ttbar semileptonic analysis is currently doing JERC before JLC.

on top of this, as far as i know, JER SFs are measured on standard (CHS) jets, without any particular jet-lepton cleaning. if that's the case, it would make more sense to apply JER SFs on the jets before JLC.

PS: ZprimeSemiLeptonic/ doesn't use this module, so this is not going to affect the latter package

**Comment by dgonzal** [comment]
Ok thanks, this sounds like useful information, I wasn't aware of this studies. I would follow the Z' semi on this. By default the jetlep cleaner will be off in the beginning.
