### ISSUE TITLE
install.sh script failure on SL7

### ISSUE THREAD

**Issue by gvonsem** [UHH2/UHH2#1511]
In the install.sh script in the branch `RunII_102X_v2`, the release CMSSW_10_2_16 is attempted to be installed on SL7. However, this CMSSW release does not appear to have an associated SL7 architecture (see [release announcement](https://hypernews.cern.ch/HyperNews/CMS/get/relAnnounce/2059.html)).

**Comment by raggleton** [comment]
Thanks for reporting - I guess we never explicitly tested this on an EL7 machine, and just put the change in `SCRAM_ARCH` "in case".

(I also never setup a CI test scenario, since it makes the CI setup much more complicated)

Since it doesn't exist, I will instead make it error if the user is on an EL7 machine

**Comment by gvonsem** [comment]
Thanks for following up! So I assume the solution for now is just to do the installation on an SL6 machine.

**Comment by raggleton** [comment]
Yes, I will also add a note to the respective wiki pages about the required machine architecture for the releases.
