### ISSUE TITLE
Issue locating JER files

### ISSUE THREAD

**Issue by jngadiub** [UHH2/UHH2#1521]
I installed and compiled UHH2 following the recipe [here](https://github.com/UHH2/UHH2/wiki/Installing,-Compiling,-Ntuples-(RunII-2016,17,18-datasets-in-CMSSW_10_2_X-v2)):

```
ssh -XY lxplus6.cern.ch
mkdir UHH2
cd UHH2
wget https://raw.githubusercontent.com/UHH2/UHH2/RunII_102X_v2/scripts/install.sh
source install.sh
cmsenv
cd ../../../SFrame
source setup.sh
make -j4
cd ../CMSSW_10_2_16/src/UHH2
make -j9
```

Then I download my [analysis code](https://github.com/jngadiub/UHHNtupleConverter.git) and compile it. When running it I get the following error:

```
 ( FATAL )  sframe_main        : app/sframe_main.cxx:70 (int main(int, char**)): STD exception caught
 ( FATAL )  sframe_main        : app/sframe_main.cxx:71 (int main(int, char**)): Message: Registry: exception while trying to build type 'UHHNtupleConverterModule': Could not locate file '2016/Summer16_25nsV1_MC_PtResolution_AK8PFchs.txt' in $CMSSW_BASE/src/{UHH2,} or $SFRAME_DIR/{UHH2,}.
 ( FATAL )  sframe_main        : app/sframe_main.cxx:72 (int main(int, char**)): --> Stopping execution
```

These files do exist though under `$CMSSW_BASE/src/UHH2/common/data` but they are not picked up.
The JER files are loaded automatically/internally from the year and collection (i.e., I do not indicate in my analysis code a custom path). Also note, that this issue does not appear when basing on the `RunII_102X_v1` branch. In fact, I noticed a difference with the `RunII_102X_v2` one:

The `RunII_102X_v2` branch comments [here](https://github.com/UHH2/UHH2/blob/RunII_102X_v2/common/include/JetCorrections.h#L276) that the path `common/data` is automatically attached  but this does not seem to be the case as you can see in the [JetCorrections.cxx#L915](https://github.com/UHH2/UHH2/blob/RunII_102X_v2/common/src/JetCorrections.cxx#L915). In contrast, this was happening in the `RunII_102X_v1` branch, i.e. at [JetCorrections.cxx#L913](https://github.com/UHH2/UHH2/blob/RunII_102X_v1/common/src/JetCorrections.cxx#L913).

Did anybody else experience this problem?

**Comment by anmalara** [comment]
Hi,
I think that switching to 102X_v2, the decision was to not use anymore the common/data/ to retrieve the JEC/JER files, since we should maintain them during the development. The choice was done together with the idea of moving the whole JER macros into something officially provided (still work in progress), even though JER has been developed and maintained in our group in the last year.

Given then, I'd say you should change the path to you txt files, into something like.
"JRDatabase/textFiles/"+jer_version+"_MC/"+jer_version+"_MC_PtResolution_"+jet_collection+".txt";
It should do the trick. In a similar way for the SF.

For the future, we can think about a new constructor when one can specify the jer_version and jet_collection directly. The downside of this approach is that, as experienced in the past, the official repository propagates the name composition in a different way across the years; therefore it's more complex to maintain all the cases.

Hope this helps and sorry for the long answer.
Let me know if you have further questions.

**Comment by jngadiub** [comment]
Thanks a lot!

Although I am not sure where to change the path to the txt file IF that file is decided centrally and automatically given the collection and the year (as it should be). This [PR#1522](https://github.com/UHH2/UHH2/pull/1522) instead seems to fix the issue as it brings things back as they were (working) in the V1 branch. Thoughts?

I understand the main (and better) idea of having a more general code but at the moment it is not working and it is causing issues to people trying to use the framework. So perhaps branch this development out of the main branch?

**Comment by mschrode** [comment]
Hi @jngadiub @anmalara , is this issue fixed? Can I close it?

**Comment by jngadiub** [comment]
Yes from side, everything works fine now. Thank you.

**Comment by mschrode** [comment]
Perfect, thanks!
