### ISSUE TITLE
EGamma postreco tools

### ISSUE THREAD

**Issue by finnlabe** [UHH2/UHH2#1570]
Currently, we are using custom code to process electrons and photons (applying IDs, corrections...). However, the EGamma POG provides what they call "post reco tools", a centrally updated python cmssw config file that handles all this. The twiki page linked [here](https://twiki.cern.ch/twiki/bin/viewauth/CMS/EgammaPostRecoRecipes) explains this in more detail. This includes the changes needed to process samples older than 106X (for example 102X) in 106X and forward, which is not possible otherwise due to changes in egamma data structure.

I thought I would open this issue to discuss how to proceed with this: do we want to switch to this central code?
In my opinion, it is beneficial to use this centrally updated module, as this will make it very easy for us to make sure that we use everything in the way the POG suggests and are up to date.

I am looking for opinions on this. I have also started to look into the actual implementation, and will comment these technical details below.

**Comment by mschrode** [comment]
Hi @finnlabe , thanks! I'm fully in favour of using centrally-provided tools as much as possible. So, if there is no strong reason *not* to use the post reco tools, I think we should switch to using them, even before we start the UL production.

**Comment by finnlabe** [comment]
Find below a few lines on a possible implementation of the central code.

In principle, this is very straight-forward: the module provides a central function, which creates a single sequence that needs to be added to the path. This looks like this:

```python
# including the package
from EgammaUser.EgammaPostRecoTools.EgammaPostRecoTools import *
 
# This is the main function:
setupEgammaPostRecoSeq(process, era='2018-Prompt') # era set fixed 2018-Prompt for testing
 
# it creates a sequence called "egammaPostRecoSeq" which can be added to the path
process.p = cms.Path(
        process.content *
        process.egammaPostRecoSeq * # new sequence added here
        process.MyNtuple
    )
```

This code updates the slimmedElectrons collection. In it, IDs are set as "userInts", similar to our slimmedElectronUSER collection. However, we store keys in our Ntuples via a tag mechanism, as seen here in [ntuple_generator.py](https://github.com/UHH2/UHH2/blob/RunII_102X_v2/core/python/ntuple_generator.py#L2123) (Line 2123). These tags are not set, so simply replacing our slimmedElectronsUSER by the new slimmedElectrons using the EgammaPostRecoSeq does not work. I am not sure what the best way to proceed would be: either we continue using the tag mechanism, which probably would require a slimmedElectronsUSER class again, or find a different way for the Ntupler to get the IDs from the "userInts"? 

Looking forward to any opinions or suggestions!

**Comment by finnlabe** [comment]
General comment: I noticed that we currently seem to have two "parallel" ways of using electron IDs. Looking at the [ElectronID class](https://github.com/UHH2/UHH2/blob/RunII_102X_v2/common/include/ElectronIds.h), we have the `ElectronTagID` which uses the tags saved during the Ntupling process, which would be now provided by the post reco tools. However, we also have in that class manual implementations of several IDs. Is this really necessary or is this just a legacy thing that could be dropped for 106X?

Edit: I believe at the same time we might discuss [this comment ](https://github.com/UHH2/UHH2/blob/RunII_106X_v1/core/python/ntuple_generator.py#L1853)in line 1853 regarding mini isolation?

**Comment by finnlabe** [comment]
I just saw that this is still open. The switch to the central modules was implemented last year, see the PR above. So if there is no protest until next week, I'll close this issue :)

**Comment by mschrode** [comment]
Yes, we can close it, thanks for spotting!

**Comment by MatthiesC** [comment]
Just for completeness: We did not so far implement the residual energy scale & smearing corrections for electrons and photons what is done with the EGammaPostRecoTools, but only used it for the correct implementation of IDs. Those corrections are computed on-the-fly during ntuple production (see the `runEnergyCorrections` argument of `setupEgammaPostRecoSeq` in [1]) but not written to the UHH2 Electron nor Photon class (this would need adjustments to `core/plugins/NtupleWriterLeptons.cxx`. However, at this stage, this is not feasible anymore since adding new members (i.e. floats holding the corrected energy values as defined in [2]) to the Electron or Photon class would make previous ntuples incompatible.

[1] https://github.com/UHH2/UHH2/blob/RunII_106X_v2/core/python/ntuple_generator.py#L1956
[2] https://twiki.cern.ch/twiki/bin/viewauth/CMS/EgammaMiniAODV2#Energy_Scale_and_Smearing
More documentation: https://twiki.cern.ch/twiki/bin/view/CMS/EgammaUL2016To2018#Scale_and_smearing_corrections_f
